version: '3'

services:
  app:
    build:
      context: .
      dockerfile: config/Dockerfile
    container_name: app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./public:/var/www:cached
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./public:/var/www:cached
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network
  db:
    image: mariadb:latest
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    env_file:
      - ./config/.env
    volumes:
      - ./database/:/var/lib/mysql/
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  database:
    driver: local